services:
  amethyst:
    image: amethyst:latest
    container_name: amethyst
    restart: always
    ports:
      # host:container
      - 3000:3000
    volumes:
      # SQLite database
      - ./data:/data
      # Uploaded images
      - ./uploads:/app/public/uploads
